language: php

php: [5.6, 7.0, 7.1]

before_script:
  - composer selfupdate
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
